### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rockscy** [devanonyme-fr/4tracks#22]
IDE: QTCreator  qt6.2.3  minGw64
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
DL
    linked by target "juce_static_lib" in directory C:/QT_Project/4tracks-master/Includes/JUCE
RT
    linked by target "juce_static_lib" in directory C:/QT_Project/4tracks-master/Includes/JUCE

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
CMake process exited with exit code 1.

**Comment by devanonyme-fr** [comment]
I think it is because CMake script works with DL and RT libraries, that are only available on Linux
Can you try on a Linux system ?
I'm working to fix that

**Comment by devanonyme-fr** [comment]
It's now fixed with commit https://github.com/devanonyme-fr/4tracks/commit/fea9d430e456f28f5220df83094c8ccd9755b247

**Comment by rockscy** [comment]
Thank you very much. It's ready to go

**Comment by JoeKenyon** [comment]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RT
    linked by target "juce_static_lib" in directory /Users/joekenyon/4tracks/Includes/JUCE
    
    
getting a similar when trying to build this in Clion for Mac 

using macOS Ventura 13.2.1

if that helps
